//alert("heli");
//document.write("heli");
//var num = prompt("enternumber", 7);
//document.write(num);
//var num = parseint(prompt("enter number"));
//document.write("<br/>");
//var name = prompt("entername","");
//document.write("hello",name);
//var age = parseInt(prompt("enter your age", 0));
//document.write("your age is", age);
//var age = parseInt(prompt("enter your age"));
//document.write("next year you will be", age + 1);
var num1 = parseInt(prompt("enter first num"));
var num2 = parseInt(prompt("enter second num"));
var plos = num1 + num2;
var kefl = num1 * num2;
var hafres = num1 - num2;
var mana = num1 / num2;
document.write("the plos is ", plos);
document.write("<br/>");
document.write("the kefl is ", kefl);
document.write("<br/>");
document.write("the hafres is ", hafres);
document.write("<br/>");
document.write("the mana is ", mana);